#!/usr/bin/python3
import time
import math
import sys
from sys import argv


def factorize(num):
    factors = []
    for i in range(2, int(math.sqrt(num)) + 1):
        while num % i == 0:
            factors.append(i)
            num //= i
    if num > 1:
        factors.append(num)
    return factors

def main(file_path):
    with open(file_path, 'r') as file:
        numbers = file.readlines()
        for number in numbers:
            num = int(number.strip())
            factors = factorize(num)
            if len(factors) >= 2:
                print(f"{num}={factors[0]}*{factors[1]}")

if __name__ == "__main__":
    file_path = sys.argv
    main(file_path)
